#!/bin/bash

set -eu

user="_prometheus"
group="_prometheus"

dscl=/usr/bin/dscl
$dscl . -read "/Users/${user}" &> /dev/null || {
    # We need to find a free UID/GID
    uid=200
    while $dscl . -list /Users uid | grep -q "\b${uid}$" || \
        $dscl . -list /Groups gid | grep -q "\b${uid}$"; do
        uid=$((uid + 1))
    done
    $dscl . -create /Groups/${group}
    $dscl . -create /Groups/${group} PrimaryGroupID ${uid}
    $dscl . -create /Groups/${group} Password "*"
    $dscl . -create /Groups/${group} RealName "Prometheus metrics monitoring"
    $dscl . -create /Users/${user}
    $dscl . -create /Users/${user} UserShell /usr/bin/false
    $dscl . -create /Users/${user} NFSHomeDirectory /var/empty
    $dscl . -create /Users/${user} PrimaryGroupID ${uid}
    $dscl . -create /Users/${user} UniqueID ${uid}
    $dscl . -create /Users/${user} Password "*"
    $dscl . -create /Users/${user} RealName "Prometheus metrics monitoring"
}

/bin/launchctl load "/Library/LaunchDaemons/io.prometheus.TimeMachineExporter.plist"
